name: emaWorkbenchTesting
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cffi=1.15.1
  - comm=0.1.2
  - debugpy=1.6.4
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.8.0
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.21.2
  - gstreamer=1.21.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.2.0
  - importlib_resources=5.10.1
  - ipykernel=6.19.3
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.3
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.0
  - jupyter_events=0.5.0
  - jupyter_server=2.0.1
  - jupyter_server_terminals=0.4.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.4
  - krb5=1.20.1
  - libclang=13.0.1
  - libcxx=14.0.6
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libglib=2.74.1
  - libiconv=1.17
  - libllvm13=13.0.1
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libvorbis=1.3.7
  - libzlib=1.2.13
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.7
  - nbconvert-core=7.2.7
  - nbconvert-pandoc=7.2.7
  - nbformat=5.7.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.78
  - openssl=3.0.7
  - packaging=22.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.0
  - ply=3.11
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.2
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.1
  - python_abi=3.10
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - readline=8.1.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.7.5
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.8.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.4
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zstd=1.5.2
  - pip:
    - altair=
    - contourpy=
    - cycler=
    - dill=
    - ema-workbench=
    - exceptiongroup=
    - fonttools=
    - iniconfig=
    - ipyparallel=
    - joblib=
    - kiwisolver=
    - matplotlib=
    - multiprocess=
    - numpy=
    - pandas=
    - patsy=
    - pillow=
    - platypus-opt=
    - pluggy=
    - pydot=
    - pyparsing=
    - pytest=
    - python-graphviz=
    - pytz=
    - salib=
    - scikit-learn=
    - scipy=
    - seaborn=
    - statsmodels=
    - threadpoolctl=
    - tomli=
    - toolz=
    - tqdm=
